# Generated by Django 5.1.3 on 2024-11-09 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название ракеты')),
                ('description', models.TextField(verbose_name='Описание')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Высота (м)')),
                ('diameter', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Диаметр (м)')),
                ('mass', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Масса (кг)')),
                ('stages', models.IntegerField(verbose_name='Количество ступеней')),
                ('first_flight', models.DateField(verbose_name='Дата первого полета')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rockets/images/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название спутника')),
                ('description', models.TextField(verbose_name='Описание')),
                ('mission_type', models.CharField(max_length=100, verbose_name='Тип миссии')),
                ('launch_date', models.DateField(verbose_name='Дата запуска')),
                ('orbit_type', models.CharField(max_length=100, verbose_name='Тип орбиты')),
                ('image', models.ImageField(blank=True, null=True, upload_to='satellites/images/', verbose_name='Изображение')),
                ('rocket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satellites', to='technology.rocket', verbose_name='Запущена на ракете')),
            ],
        ),
    ]
